services:
  db:
    image: postgres:17
    container_name: sanich-db
    restart: unless-stopped

    environment:
      POSTGRES_DB: sanich
      POSTGRES_USER: sanich
      POSTGRES_PASSWORD: sanich

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: